# Generated by Django 3.0 on 2019-12-03 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries_ion_frac',
            name='description',
        ),
        migrations.RemoveField(
            model_name='entries_ion_frac',
            name='reference',
        ),
        migrations.AlterField(
            model_name='entries_ion_frac',
            name='err_down',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entries_ion_frac',
            name='err_down2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entries_ion_frac',
            name='err_up',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entries_ion_frac',
            name='err_up2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ion_frac_refs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField()),
                ('description', models.TextField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constraints.Entries_ion_frac')),
            ],
        ),
    ]
