# Generated by Django 3.0 on 2019-12-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0002_auto_20191203_1035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ion_frac_refs',
        ),
    ]
