# Generated by Django 3.0 on 2019-12-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0003_delete_ion_frac_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries_ion_frac',
            name='description',
            field=models.TextField(default='that'),
        ),
        migrations.AddField(
            model_name='entries_ion_frac',
            name='reference',
            field=models.TextField(default='this'),
        ),
    ]
