# Generated by Django 3.0 on 2019-12-05 12:31

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0004_auto_20191204_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries_flux_ps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionary_tag', models.TextField()),
                ('redshift', models.FloatField()),
                ('ks', models.FloatField()),
                ('flux_ps', models.FloatField()),
                ('err_up', models.FloatField()),
                ('err_down', models.FloatField()),
                ('err_up2', models.FloatField()),
                ('err_down2', models.FloatField()),
                ('upper_lim', models.BooleanField()),
                ('lower_lim', models.BooleanField()),
                ('reference', models.TextField(default='this')),
                ('description', models.TextField(default='that')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='entries_ion_frac',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
