# Generated by Django 3.0 on 2019-12-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0006_auto_20191211_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries_ion_frac',
            name='redshift_exp',
        ),
        migrations.AlterField(
            model_name='entries_ion_frac',
            name='err_down',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='entries_ion_frac',
            name='err_down2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='entries_ion_frac',
            name='err_up',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='entries_ion_frac',
            name='err_up2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='entries_ion_frac',
            name='ion_frac',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='entries_ion_frac',
            name='red_list',
            field=models.ManyToManyField(related_name='_entries_ion_frac_red_list_+', to='constraints.Entries_ion_frac'),
        ),
        migrations.AlterField(
            model_name='entries_ion_frac',
            name='redshift',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
