# Generated by Django 3.0 on 2019-12-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0007_auto_20191211_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries_ion_frac',
            name='red_list',
        ),
        migrations.AlterField(
            model_name='entries_ion_frac',
            name='lower_lim',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='entries_ion_frac',
            name='upper_lim',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
